swagger: '2.0'
schemes:
  - https
host: analyticsreporting.googleapis.com
basePath: /
info:
  contact:
    description: 'TBD'
    name: Google
    url: 'https://google.com'
  description: Accesses Analytics report data.
  title: Analytics Reporting
  version: v4
  x-apiClientRegistration:
    description: 'TBD'
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - analytics
      description: 'TBD'
  x-logo:
    description: 'TBD'
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.6.2
      format: google
      url: 'https://analyticsreporting.googleapis.com/$discovery/rest?version=v4'
      version: v1
      description: 'TBD'
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: analyticsreporting
externalDocs:
  description: 'TBD'
  url: 'https://developers.google.com/analytics/devguides/reporting/core/v4/'
securityDefinitions:
  description: 'TBD'
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/analytics': View and manage your Google Analytics data
      'https://www.googleapis.com/auth/analytics.readonly': View your Google Analytics data
    type: oauth2
parameters:
  description: 'TBD'
  $.xgafv:
    description: V1 error format.
    enum:
      - '1'
      - '2'
    in: query
    name: $.xgafv
    type: string
  access_token:
    description: OAuth access token.
    in: query
    name: access_token
    type: string
  alt:
    default: json
    description: Data format for response.
    enum:
      - json
      - media
      - proto
    in: query
    name: alt
    type: string
  bearer_token:
    description: OAuth bearer token.
    in: query
    name: bearer_token
    type: string
  callback:
    description: JSONP
    in: query
    name: callback
    type: string
  fields:
    description: Selector specifying which fields to include in a partial response.
    in: query
    name: fields
    type: string
  key:
    description: 'API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.'
    in: query
    name: key
    type: string
  oauth_token:
    description: OAuth 2.0 token for the current user.
    in: query
    name: oauth_token
    type: string
  pp:
    default: true
    description: Pretty-print response.
    in: query
    name: pp
    type: boolean
  prettyPrint:
    default: true
    description: Returns response with indentations and line breaks.
    in: query
    name: prettyPrint
    type: boolean
  quotaUser:
    description: 'Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.'
    in: query
    name: quotaUser
    type: string
  uploadType:
    description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
    in: query
    name: uploadType
    type: string
  upload_protocol:
    description: 'Upload protocol for media (e.g. "raw", "multipart").'
    in: query
    name: upload_protocol
    type: string
tags:
  - name: reports
    description: 'TBD'
paths:
  /v4/reports:batchGet:
    parameters:
      - $ref: '#/parameters/$.xgafv'
      - $ref: '#/parameters/access_token'
      - $ref: '#/parameters/alt'
      - $ref: '#/parameters/bearer_token'
      - $ref: '#/parameters/callback'
      - $ref: '#/parameters/fields'
      - $ref: '#/parameters/key'
      - $ref: '#/parameters/oauth_token'
      - $ref: '#/parameters/pp'
      - $ref: '#/parameters/prettyPrint'
      - $ref: '#/parameters/quotaUser'
      - $ref: '#/parameters/uploadType'
      - $ref: '#/parameters/upload_protocol'
    post:
      description: Returns the Analytics data.
      operationId: analyticsreporting.reports.batchGet
      parameters:
        - in: body
          name: body
          description: 'TBD'
          schema:
            $ref: '#/definitions/GetReportsRequest'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/GetReportsResponse'
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics'
          description: 'TBD'
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics.readonly'
          description: 'TBD'
      tags:
        - reports
          description: 'TBD'